docs_dir: doc
# site_name: Toolio—OpenAI-like HTTP server API implementation which supports tool-calling and other structured LLM response generation (e.g. make it conform to a JSON schema)
site_name: Toolio—Schema-controlled responses and tool-calling for LLMs on Mac
theme:
  name: material